### ISSUE TITLE
Can't run via docker

### ISSUE THREAD

**Issue by cmielke-vir** [soedinglab/MMseqs2-App#24]
When attempting to bring docker-compose up, the api image crashes with the following output :

mmseqs-web-api_1        | panic: invalid character 'e' in numeric literal
mmseqs-web-api_1        |
mmseqs-web-api_1        | goroutine 20 [running]:
mmseqs-web-api_1        | main.server.func1(0xc0002a4780, 0x8d1538, 0xc0000b4350)
mmseqs-web-api_1        |       /opt/mmseqs-web/server.go:30 +0x28c
mmseqs-web-api_1        | created by main.server
mmseqs-web-api_1        |       /opt/mmseqs-web/server.go:27 +0xb9
dockercompose_mmseqs-web-api_1 exited with code 2

This is my first time interpreting stack traces for Golang, but it appears to be referencing this line in server.go ?
		databases, err := Databases(config.Paths.Databases, false)

The config.json file in ./docker-compose isn't edited in any way.

**Comment by cmielke-vir** [comment]
Ah-hah! Found an abberant "-e" in the params file for pdb70! I think the echo command in the downloader script may have put it there for some reason

-e {
    "status":"RUNNING",
   "display" ...... etc
